enableMessage: Citadel winter is enabled!
freezeDamageTickMultiplier: 1

heartBeat:
  minVolume: 0.1
  maxVolume: 1
  minPeriod: 40
  maxPeriod: 400
  tickRate: 1

temperatures:
  heat: 60
  default: 36.6
  cold: 14
  freeze: 0

colors:
  info: 80bdbd
  heat: 942a19
  warm: 9ac967
  default: 75bda0
  cold: 45507d
  freeze: 3b3b5b

blocks:
  TORCH:
    radius: 5
    heat: 0.01
    fadeTime: 5
  SOUL_TORCH:
    radius: 4
    heat: 0.008
    fadeTime: 10
  LANTERN:
    radius: 6
    heat: 0.005
    fadeTime: -1
  SOUL_LANTERN:
    radius: 5
    heat: 0.004
    fadeTime: -1
  CAMPFIRE:
    radius: 13
    heat: 0.1
    fadeTime: 10
  SOUL_CAMPFIRE:
    radius: 12
    heat: 0.08
    fadeTime: 20
