enableMessage: Citadel winter is enabled!
freezeDamageTickMultiplier: 1
maxFreezeTick: 150
coldPerTick: -0.002
netherHeat: 1
changingTemperatureMultiplier: 1
insulatedArmorMultiplier: 0.9

blizzard:
  radiusMultiplier: 64
  maxBlizzard: 4
  chunks:
    ventus:
      cold: 1
      fade: 1
      allowFire: true
      damage: 0
    frigus:
      cold: 2
      fade: 2
      allowFire: true
      damage: 0
    nix:
      cold: 4
      fade: 8
      allowFire: true
      damage: 1
    glacies:
      cold: 8
      fade: 8
      allowFire: false
      damage: 4
    tempestas:
      cold: 16
      fade: 16
      allowFire: false
      damage: 8

height:
  groundHeatLowest: 40
  groundHeatHighest: 63

tickRates:
  heartBeat: 1
  coldDamage: 40
  updateTemperature: 1
  manageTemperature: 1
  blocksFade: 1
  blizzardDamage: 20

heartBeat:
  minVolume: 0.1
  maxVolume: 1
  minPeriod: 40
  maxPeriod: 400
  tickRate: 1

temperatures:
  heat: 60
  default: 36.6
  cold: 14
  freeze: 0

colors:
  info: 80bdbd
  heat: 942a19
  warm: 9ac967
  default: 75bda0
  cold: 45507d
  freeze: 3b3b5b

heat:
  maxRadius: 25
  heatItem: 0.0025

# Время в минутах
blocks:
  TORCH:
    radius: 5
    heat: 0.01
    fadeTime: 5
  WALL_TORCH:
    radius: 5
    heat: 0.01
    fadeTime: 5
  SOUL_TORCH:
    radius: 4
    heat: 0.008
    fadeTime: 10
  SOUL_WALL_TORCH:
    radius: 4
    heat: 0.008
    fadeTime: 10
  LANTERN:
    radius: 6
    heat: 0.005
    fadeTime: 0
  SOUL_LANTERN:
    radius: 5
    heat: 0.004
    fadeTime: 0
  CAMPFIRE:
    radius: 13
    heat: 0.1
    fadeTime: 10
    interactionOffset: 0.4
  SOUL_CAMPFIRE:
    radius: 12
    heat: 0.08
    fadeTime: 20
  FURNACE:
    radius: 20
    heat: 0.5
    fadeTime: 0
  BLAST_FURNACE:
    radius: 25
    heat: 0.5
    fadeTime: 0
  SMOKER:
    radius: 22
    heat: 0.5
    fadeTime: 0

#Время в тиках
fuel:
  STICK: 600
  LOG: 6000
  STEM: 6100
  WOOD: 8000
  HYPHAE: 8100
  PLANKS: 1500
  COAL: 6500